#!/bin/bash

# LICENSE: BSD
# VERSION: 1.1.3
# https://github.com/kai3341/zerod

ZEROD=`basename "$0"`
CWD="$PWD"

ZEROD_DIR=".${ZEROD}"
CONFIG="${ZEROD_DIR}/config"
ZEROD_TEMP_DIR="${ZEROD_DIR}/zerod.temp"  # put zerod.temp/ into .gitignore
ZEROD_PID_DIR="${ZEROD_TEMP_DIR}/pid"
ZEROD_RESTART_PID_DIR="${ZEROD_TEMP_DIR}/pid_restart"
LOG="${ZEROD_TEMP_DIR}/log"
SCRIPT_DIR="${ZEROD_DIR}/scripts"

COLOR_OUT=$'\033[0;36m'
COLOR_ERR=$'\033[0;31m'
COLOR_DBG=$'\033[0;32m'
COLOR_CRT=$'\033[0;41m'
COLOR_CLR=$'\033[0m'

LOG_STDOUT='O|'
LOG_STDERR='E|'
LOG__ZEROD='X|'

STARTUP_HASH=`last reboot --limit 1 | head -n 1 | md5sum  | cut -d ' ' -f 1`

info() { echo "${COLOR_DBG}$@${COLOR_CLR}"; }
crit() { echo "${COLOR_CRT}$@${COLOR_CLR}" >&2; }

pidlist_aux() {
    for pidfile in `ls -1 "${1}/"`; do
        pidfilepath="${1}/${pidfile}"
        [ "$STARTUP_HASH" == `cat "$pidfilepath"` ] && echo $pidfile || rm -f "$pidfilepath"
    done
}

pidlist() { pidlist_aux "${ZEROD_PID_DIR}"; }
pidlist_restart() { pidlist_aux "${ZEROD_RESTART_PID_DIR}"; }

# waitpid: Wait untill process is stoped

waitpid__tail() { tail --pid=$1 -f /dev/null; }
waitpid__lsof() { lsof -wp $1 +r 1 &>/dev/null; }

# unbuffered

unbuffered__stdbuf() { echo stdbuf -oL $@; }
unbuffered__null() { echo $@; }

# HELP

HELP_USAGE="\
USAGE:
$0 init
$0 start
$0 stop
$0 restart
$0 log tail
$0 log clear
$0 ps
$0 run  # script
"

CONFIG_EXAMPLE="\
CMD=\"/usr/bin/python3 /usr/bin/dstat\"  # required
# RESTART=1  # optional. Restart command when it stoped
# MANY=1  # optional. Allow to start many instancies
"

HELP_CONFIG="\
Config file \`$CONFIG\`:
$CONFIG_EXAMPLE"

show_help() {
    echo "$HELP_USAGE"
    show_help__scripts
    echo "$HELP_CONFIG"
}

show_help__scripts() {
    if [ -d "$SCRIPT_DIR" ]; then
        echo "SCRIPTS AVAILABLE:"
        ls -1Q "$SCRIPT_DIR" | xargs -rI {} echo $0 run \"{}\"
        echo
    else
        echo "You may to create \`$SCRIPT_DIR\` directory to put scripts here"
    fi
    echo "Scripts support passing arguments: \`$0 run example arg1 arg2 ...\`"
    echo "Script will be called from current directory \`$CWD\` with extra" \
    "environment variable \`ZEROD\` refering this script: \`$0\`"
    echo
}

not_found() {
    crit "$1 found in current working directory: \`$CWD\`. You have to create it"
    info "You may run \`$ZEROD init\` to create config examle"
    echo && show_help && exit 1
}

do_init() {
    [ ! -d "$ZEROD_DIR" ] && mkdir "$ZEROD_DIR"
    [ ! -d "$SCRIPT_DIR" ] && mkdir "$SCRIPT_DIR"
    [ -f "$CONFIG" ] && crit "Config \`$CONFIG\` already exists" && exit 1
    echo "$CONFIG_EXAMPLE" > "$CONFIG"
    exit 0
}

# === OS compat ===

if [[ "$OSTYPE" =~ ^linux ]]; then
    waitpid=waitpid__tail
    unbuffered=unbuffered__stdbuf
elif [[ "$OSTYPE" =~ ^darwin ]]; then
    waitpid=waitpid__lsof
    unbuffered=unbuffered__null
else
    crit "Unknown platform! Can't run" && exit 1
fi

waitpids() { for i in "$@"; do $waitpid $i; done; }

tolog_template() { echo "echo \"${LOG__ZEROD}\$(date \"+%F|%T\")|$1\" >> \"$LOG\""; }
TOLOG=`tolog_template '$@'`

zerod_log() { info $@; eval $TOLOG; }

stop_pids_aux() {
    MESSAGE1="$1"
    MESSAGE2="$2"
    PID_DIR="$3"
    shift 3
    if [ -n "$1" ]; then
        zerod_log "${MESSAGE1}: $@"
        kill $@
        waitpids $@
        for pid in $@; do rm -f "${PID_DIR}/${pid}"; done
        zerod_log "${MESSAGE2}: $@"
    fi
}

stop_pids() { stop_pids_aux "Stopping" "+Stopped" "$ZEROD_PID_DIR" $@; }
stop_master_pids() { stop_pids_aux "Stopping master" "+Stopped master" "$ZEROD_RESTART_PID_DIR" $@; }

logging_handle() {
    $unbuffered awk \'{printf \"$1\" strftime\(\"%F\|%T\|\", systime\(\)\) \$0 \"\\n\"}\'
}

# === SETUP ===

[ "$1" == "init" ] && do_init

[ ! -d "$ZEROD_DIR" ] && not_found "No directory \`$ZEROD_DIR\`"
[ ! -f "$CONFIG" ] && not_found "No config file \`$CONFIG\`"

mkdir -p "$ZEROD_TEMP_DIR" "$ZEROD_PID_DIR" "$ZEROD_RESTART_PID_DIR"

. "$CONFIG"

[ -z "$CMD" ] && crit "Required parameter \`CMD\` not set" && show_help && exit 1

TOLOG_STOPPED="$(tolog_template "Finished: \\\`\$!\\\` stopped with returncode: \\\`\$RETURNCODE\\\`")"
RUNCMD="${CMD} & PIDFILE=\"${ZEROD_PID_DIR}/\$!\"; echo -n ${STARTUP_HASH} > \"\$PIDFILE\"; wait \$!; RETURNCODE=\$?; ${TOLOG_STOPPED}; rm -f \"\$PIDFILE\"" #"

if [ -n "$RESTART" ]; then
    RUNCMD="echo -n ${STARTUP_HASH} > \"${ZEROD_RESTART_PID_DIR}/\$\$\"; while true; do ${RUNCMD}; sleep 1; done;"
fi

RUNCMD="bash -c '${RUNCMD}'"

COLORIZE=""\
"s%^${LOG_STDOUT}%${COLOR_OUT}%g;"\
"s%^${LOG_STDERR}%${COLOR_ERR}%g;"\
"s%^${LOG__ZEROD}%${COLOR_DBG}%g;"\
"s%$%${COLOR_CLR}%g"

# ===

case $1 in
    start)
        shift
        if [ -z "$MANY" ]; then
            pids=`pidlist`
            [ -n "$pids" ] && crit "Already runing: ${pids}" && exit 1
        fi
        zerod_log "Starting: \`$CMD\`"
        bash -c "nohup ${RUNCMD} \
            > >(`logging_handle $LOG_STDOUT` >> '$LOG') \
            2> >(`logging_handle $LOG_STDERR` >> '$LOG') &";
    ;;

    stop)
        shift
        [ -n "$RESTART" ] && stop_master_pids `pidlist_restart`
        stop_pids `pidlist`
    ;;

    restart)
        "$0" stop
        "$0" start
    ;;

    log)
        shift
        case $1 in
            tail)
                tail -n 300 -f "$LOG" | `$unbuffered sed -e "$COLORIZE"`
            ;;

            clear)
                echo -n > "$LOG"
            ;;

            *)
                show_help
                exit 1
            ;;
        esac;
    ;;

    ps)
        shift
        pids=`pidlist`
        [ -n "$pids" ] && ps -f `echo $pids | xargs -I {} echo -p {}` || true
    ;;

    run)
        shift
        [ -z "$1" ] && show_help__scripts && exit 1
        script="${SCRIPT_DIR}/$1"
        [ ! -f "$script" ] && \
            crit "Script \`$1\` not found in \`${SCRIPT_DIR}\`" && exit 1
        shift
        ZEROD="$0" "$script" $@
    ;;

    --help)
        show_help
    ;;

    *)
        show_help
        exit 1
    ;;
esac;
